### PR TITLE
Github CI Actions

### PR DESCRIPTION
**Pull request by smasoka**
PR not to be merged for now.

### CODE REVIEW

**Comment by bennahugo** [comment]
ok to test

**Comment by sjperkins** [comment]
Github Actions run through: https://github.com/smasoka/tricolour/tree/github-actions

**Review by sjperkins — APPROVED** [review]

**Comment by sjperkins** [comment]
@smasoka The travis.yml and .travis directory should also be removed

**Comment by sjperkins** [comment]
I've deleted the travis webhook

**Review by sjperkins — CHANGES_REQUESTED** [review]
Sorry I should have reviewed more thoroughly.

The following needs doing:

1. Removing travis.yml and .travis directory
2. Update the CHANGELOG with this PR

**Review by sjperkins — APPROVED** [review]

**Comment by sjperkins** [comment]
Thanks @smasoka!

**Pull request merged**
