### PR TITLE
Revert "Obfuscate releases"

### PR DESCRIPTION
**Pull request by sjperkins**
Reverts ska-sa/tricolour#63

### CODE REVIEW

**Comment by bennahugo** [comment]
please remember to cherry pick the fixes for numpy

**Comment by sjperkins** [comment]
> please remember to cherry pick the fixes for numpy

I'm sorry, I have no idea what you mean by this. Could you please explain further?

**Comment by sjperkins** [comment]
> There are changes to the driver fixing issues introduced by the october/november release of numpy.

Which driver? Can you please point me at a link describing this? I can't see any driver in #63

**Comment by sjperkins** [comment]
I think it would probably be a lot simpler to just merge #64  and release 0.1.7

**Comment by bennahugo** [comment]
https://github.com/ska-sa/tricolour/pull/63/commits/dd87bfed945a1268b07f254955d2eda5f69c4d83

**Comment by sjperkins** [comment]
OK got it

**Comment by sjperkins** [comment]
I'll put https://github.com/ska-sa/tricolour/commit/dd87bfed945a1268b07f254955d2eda5f69c4d83 in #64

**Pull request merged**
