### PR TITLE
Prepare for 0.1.7 release

### PR DESCRIPTION
**Pull request by sjperkins**

### CODE REVIEW

**Comment by sjperkins** [comment]
@bennahugo Will you please review? The dask-ms upgrade was tested in https://github.com/ska-sa/meerkathi/issues/723#issuecomment-567431537.

**Comment by bennahugo** [comment]
@sjperkins currently 0.1.6 in #63 needs to be merged first because it is the latest production version. I've already bumped up the versions. if we don't merge the branches the commits that form the revision tags will be lost.

**Comment by bennahugo** [comment]
Aside from that the only thing that needs to be fixed is the notice that is printed in the driver

**Comment by bennahugo** [comment]
This also needs a basic dockerfile for building releases.

**Comment by sjperkins** [comment]
> This also needs a basic dockerfile for building releases.

Generally my strategy for building releases has been to use travis's auto-deploy mechanisms. See 
https://github.com/ska-sa/codex-africanus/blob/master/.travis.yml for instance. I think the way forward is to replace our jenkins build with a travis build. I'll also do that as part of this PR.

**Comment by bennahugo** [comment]
We don't have credits to test builds more than 40 minutes in duration. This is why I prefer Jenkins.

**Comment by sjperkins** [comment]
> We don't have credits to test builds more than 40 minutes in duration. This is why I prefer Jenkins

The test cases only take 7 minutes to run at present. I think we can cross that bridge when we come to it. But I'll also have to see whether travis can run tricolour...

**Pull request merged**
